### POST request to add new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Kartheek",
  "address": "Guntur",
  "dateOfBirth": "2004-06-19",
  "email": "kartheek5050450@gmail.com",
  "registeredDate": "2023-11-10"
}

###